[package]
name = "bitviz-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bitviz = { version = "0.1.0", path = "../bitviz" }
byteorder = "1.5.0"
clap = { version = "4.5.20", features = ["derive"] }
either = "1.13.0"
svg = "0.18.0"

[[bin]]
name = "bitviz"
path = "src/main.rs"
